# ~/.config/starship.toml

palette = "srcery"

[palettes.srcery]
black = "#1C1B19"
bright-black = "#918175"
red = "#EF2F27"
bright-red = "#F75341"
green = "#519F50"
bright-green = "#98BC37"
yellow = "#FBB829"
bright-yellow = "#FED06E"
blue = "#2C78BF"
bright-blue = "#68A8E4"
purple = "#E02C6D"
bright-purple = "#FF5C8F"
cyan = "#0AAEB3"
bright-cyan = "#2BE4D0"
white = "#BAA67F"
bright-white = "#FCE8C3"

[palettes.dimmed_monokai]
black = "#3A3D43"
bright-black = "#888987"
red = "#BE3F48"
bright-red = "#FB001F"
green = "#879A3B"
bright-green = "#0F722F"
yellow = "#C5A635"
bright-yellow = "#C47033"
blue = "#4F76A1"
bright-blue = "#186DE3"
purple = "#855C8D"
bright-purple = "#FB0067"
cyan = "#578FA4"
bright-cyan = "#2E706D"
white = "#B9BCBA"
bright-white = "#FDFFB9"

[battery]
full_symbol = "󰁹"
charging_symbol = ""
discharging_symbol = "󱐋"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold green)"

[cmd_duration]
min_time = 10_000                    # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style) "

[directory]
read_only = "  "
truncate_to_repo = true
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
repo_root_style = "bold bright-blue"
truncation_length = 8
truncation_symbol = "/"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold bright-white"
read_only_style = "bold yellow"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = ""
style = "bold green"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "[󰞇](bold red) "
ahead = "[](bold green)×${count} "
behind = "[](bold red)×${count} "
diverged = "[](bold white)[](bold green)×${ahead_count} [](bold red)×${behind_count}"
untracked = "[󱜳](bold red)×${count} "
stashed = " "
modified = "[](bold yellow)×${count} "
staged = "[](bold green)×${count} "
renamed = "[󰑕](bold yellow)×${count} "
deleted = "[](bold red)×${count} "
# style = "bright-white"
format = '\[$all_status$ahead_behind\] '

[hostname]
ssh_only = true
format = "<[$hostname]($style)> "
trim_at = "-"
style = "bold blink underline purple"
disabled = false

[julia]
format = "[$symbol$version]($style) "
symbol = ""
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold white"
disabled = false
symbol = ""

[package]
disabled = true

[python]
format = "[${symbol}${pyenv_prefix}(${version} )]($style)[(\\($virtualenv\\))](bold bright-green) "
style = "bold green"
symbol = ""

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[time]
time_format = "%T"
format = " $time($style) "
style = "bright-white"
disabled = false

[typst]
format = "[$symbol($version)]($style) "
style = "bold bright-blue"

[username]
format = "[$user]($style) on "
style_user = "bold yellow"
show_always = false

[nodejs]
format = "via [$version](bold green) "
